import streamlit as str
import tensorflow as tf
from tensorflow.keras.preprocessing import image
import numpy as np
from PIL import Image

# 1. Title and Heading Set
str.title("🤖 Real vs AI-Generated Image Detector")
str.write("Upload any image to check if it's Real or generated by AI.")

# 2. Saved model (.keras format) Load
@str.cache_resource
def load_my_model():
    # Yeh aapke Downloads folder mein pari 'real_vs_ai_model.keras' file ko load karega
    return tf.keras.models.load_model('real_vs_ai_model.keras')

try:
    model = load_my_model()
except Exception as e:
    str.error(f"Error loading model file: {e}")
    str.info("Pakka kar lein ke 'real_vs_ai_model.keras' file aapke Downloads folder mein hi pari hai.")

# 3. File Upload Button 
uploaded_file = str.file_uploader("Choose an image...", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    # Screen par uploaded image dikhana
    img = Image.open(uploaded_file)
    str.image(img, caption='Uploaded Image.', use_container_width=True)
    str.write("Analyzing image...")

    # 4. Image Preprocessing (Model input size 224x224)
    img_resized = img.resize((224, 224))
    img_array = image.img_to_array(img_resized)
    img_array = np.expand_dims(img_array, axis=0)
    img_array /= 255.0  # Normalize karna

    # 5. Prediction from Model
    prediction = model.predict(img_array)
    prediction_score = prediction[0][0]

    # 6. Result Show on Screen
    str.subheader("📊 Output Result:")
    str.write(f"Model Confidence Score: {prediction_score:.4f}")

    # NEW THRESHOLD FIX (According to model):
    # Agar score 0.22 se bara hai toh AI hai, agar 0.22 se chota hai toh Real hai.
    threshold = 0.22

    if prediction_score > threshold:
        confidence = (prediction_score) * 100
        if confidence > 100: confidence = 100
        str.error(f"🤖 AI-Generated Image (Confidence: {confidence:.2f}%)")
    else:
        confidence = (1 - prediction_score) * 100
        if confidence > 100: confidence = 100
        str.success(f"📷 Real Image (Confidence: {confidence:.2f}%)")